name: Retrain Model

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.13"

      - run: pip install mlflow pandas numpy scikit-learn

      - name: Run MLflow Project
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          cd MLProject
          mlflow run . --env-manager local
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/mlruns

      - name: Check mlruns
        run: |
          find . -type d -name "mlruns"

      - name: Commit MLflow artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update MLflow artifacts
          file_pattern: MLProject/mlruns/*

      - name: Show files
        run: |
          pwd
          ls -R

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eksperimen_sml_akira-rian-satya-dhamma:latest ./MLProject/docker_test

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/eksperimen_sml_akira-rian-satya-dhamma:latest
